services:
  app:
    depends_on:
      - db
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    command: >
      sh -c "
        if [ \"$STAGE\" = \"prod\" ]; then
          npx prisma migrate deploy &&
          node dist/main.js;
        else
          npx prisma migrate dev &&
          npm run start:dev;
        fi
      "
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: qr-sena-app
    ports:
      - ${PORT}:${PORT}
    environment:
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}
      PROD_ACCESS_TOKEN: ${PROD_ACCESS_TOKEN}
      DEV_ACCESS_TOKEN: ${DEV_ACCESS_TOKEN}
      DO_SPACE_REGION: ${DO_SPACE_REGION}
      DO_SPACES_CDN_URL: ${DO_SPACES_CDN_URL}
      DO_SPACES_URL: ${DO_SPACES_URL}
      DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}
      DO_SPACES_ACCESS_KEY: ${DO_SPACES_ACCESS_KEY}
      DO_SPACE_SECRET_KEY: ${DO_SPACE_SECRET_KEY}

  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false